/// Generated by DeviceTypesGen

import SwiftUI

public extension PreviewDevice {
    /// iPhone 4s
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-4s
    static let iPhone4s: PreviewDevice = PreviewDevice(rawValue: "iPhone 4s")

    /// iPhone 5
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-5
    static let iPhone5: PreviewDevice = PreviewDevice(rawValue: "iPhone 5")

    /// iPhone 5s
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-5s
    static let iPhone5s: PreviewDevice = PreviewDevice(rawValue: "iPhone 5s")

    /// iPhone 6 Plus
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus
    static let iPhone6Plus: PreviewDevice = PreviewDevice(rawValue: "iPhone 6 Plus")

    /// iPhone 6
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-6
    static let iPhone6: PreviewDevice = PreviewDevice(rawValue: "iPhone 6")

    /// iPhone 6s
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-6s
    static let iPhone6s: PreviewDevice = PreviewDevice(rawValue: "iPhone 6s")

    /// iPhone 6s Plus
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-6s-Plus
    static let iPhone6sPlus: PreviewDevice = PreviewDevice(rawValue: "iPhone 6s Plus")

    /// iPhone SE (1st generation)
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-SE
    static let iPhoneSE_1stGeneration: PreviewDevice = PreviewDevice(rawValue: "iPhone SE (1st generation)")

    /// iPhone 7
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-7
    static let iPhone7: PreviewDevice = PreviewDevice(rawValue: "iPhone 7")

    /// iPhone 7 Plus
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-7-Plus
    static let iPhone7Plus: PreviewDevice = PreviewDevice(rawValue: "iPhone 7 Plus")

    /// iPhone 8
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-8
    static let iPhone8: PreviewDevice = PreviewDevice(rawValue: "iPhone 8")

    /// iPhone 8 Plus
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-8-Plus
    static let iPhone8Plus: PreviewDevice = PreviewDevice(rawValue: "iPhone 8 Plus")

    /// iPhone X
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-X
    static let iPhoneX: PreviewDevice = PreviewDevice(rawValue: "iPhone X")

    /// iPhone Xs
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-XS
    static let iPhoneXs: PreviewDevice = PreviewDevice(rawValue: "iPhone Xs")

    /// iPhone Xs Max
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-XS-Max
    static let iPhoneXsMax: PreviewDevice = PreviewDevice(rawValue: "iPhone Xs Max")

    /// iPhone Xʀ
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-XR
    static let iPhoneXʀ: PreviewDevice = PreviewDevice(rawValue: "iPhone Xʀ")

    /// iPhone 11
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-11
    static let iPhone11: PreviewDevice = PreviewDevice(rawValue: "iPhone 11")

    /// iPhone 11 Pro
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-11-Pro
    static let iPhone11Pro: PreviewDevice = PreviewDevice(rawValue: "iPhone 11 Pro")

    /// iPhone 11 Pro Max
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-11-Pro-Max
    static let iPhone11ProMax: PreviewDevice = PreviewDevice(rawValue: "iPhone 11 Pro Max")

    /// iPhone SE (2nd generation)
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-SE--2nd-generation-
    static let iPhoneSE_2ndGeneration: PreviewDevice = PreviewDevice(rawValue: "iPhone SE (2nd generation)")

    /// iPhone 12 mini
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-12-mini
    static let iPhone12Mini: PreviewDevice = PreviewDevice(rawValue: "iPhone 12 mini")

    /// iPhone 12
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-12
    static let iPhone12: PreviewDevice = PreviewDevice(rawValue: "iPhone 12")

    /// iPhone 12 Pro
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-12-Pro
    static let iPhone12Pro: PreviewDevice = PreviewDevice(rawValue: "iPhone 12 Pro")

    /// iPhone 12 Pro Max
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-12-Pro-Max
    static let iPhone12ProMax: PreviewDevice = PreviewDevice(rawValue: "iPhone 12 Pro Max")

    /// iPod touch (7th generation)
    /// com.apple.CoreSimulator.SimDeviceType.iPod-touch--7th-generation-
    static let iPodTouch_7thGeneration: PreviewDevice = PreviewDevice(rawValue: "iPod touch (7th generation)")

    /// iPad 2
    /// com.apple.CoreSimulator.SimDeviceType.iPad-2
    static let iPad2: PreviewDevice = PreviewDevice(rawValue: "iPad 2")

    /// iPad Retina
    /// com.apple.CoreSimulator.SimDeviceType.iPad-Retina
    static let iPadRetina: PreviewDevice = PreviewDevice(rawValue: "iPad Retina")

    /// iPad Air
    /// com.apple.CoreSimulator.SimDeviceType.iPad-Air
    static let iPadAir: PreviewDevice = PreviewDevice(rawValue: "iPad Air")

    /// iPad mini 2
    /// com.apple.CoreSimulator.SimDeviceType.iPad-mini-2
    static let iPadMini2: PreviewDevice = PreviewDevice(rawValue: "iPad mini 2")

    /// iPad mini 3
    /// com.apple.CoreSimulator.SimDeviceType.iPad-mini-3
    static let iPadMini3: PreviewDevice = PreviewDevice(rawValue: "iPad mini 3")

    /// iPad mini 4
    /// com.apple.CoreSimulator.SimDeviceType.iPad-mini-4
    static let iPadMini4: PreviewDevice = PreviewDevice(rawValue: "iPad mini 4")

    /// iPad Air 2
    /// com.apple.CoreSimulator.SimDeviceType.iPad-Air-2
    static let iPadAir2: PreviewDevice = PreviewDevice(rawValue: "iPad Air 2")

    /// iPad Pro (9.7-inch)
    /// com.apple.CoreSimulator.SimDeviceType.iPad-Pro--9-7-inch-
    static let iPadPro_9_7_inch: PreviewDevice = PreviewDevice(rawValue: "iPad Pro (9.7-inch)")

    /// iPad Pro (12.9-inch) (1st generation)
    /// com.apple.CoreSimulator.SimDeviceType.iPad-Pro
    static let iPadPro_12_9_inch_1stGeneration: PreviewDevice = PreviewDevice(rawValue: "iPad Pro (12.9-inch) (1st generation)")

    /// iPad (5th generation)
    /// com.apple.CoreSimulator.SimDeviceType.iPad--5th-generation-
    static let iPad_5thGeneration: PreviewDevice = PreviewDevice(rawValue: "iPad (5th generation)")

    /// iPad Pro (12.9-inch) (2nd generation)
    /// com.apple.CoreSimulator.SimDeviceType.iPad-Pro--12-9-inch---2nd-generation-
    static let iPadPro_12_9_inch_2ndGeneration: PreviewDevice = PreviewDevice(rawValue: "iPad Pro (12.9-inch) (2nd generation)")

    /// iPad Pro (10.5-inch)
    /// com.apple.CoreSimulator.SimDeviceType.iPad-Pro--10-5-inch-
    static let iPadPro_10_5_inch: PreviewDevice = PreviewDevice(rawValue: "iPad Pro (10.5-inch)")

    /// iPad (6th generation)
    /// com.apple.CoreSimulator.SimDeviceType.iPad--6th-generation-
    static let iPad_6thGeneration: PreviewDevice = PreviewDevice(rawValue: "iPad (6th generation)")

    /// iPad (7th generation)
    /// com.apple.CoreSimulator.SimDeviceType.iPad--7th-generation-
    static let iPad_7thGeneration: PreviewDevice = PreviewDevice(rawValue: "iPad (7th generation)")

    /// iPad Pro (11-inch) (1st generation)
    /// com.apple.CoreSimulator.SimDeviceType.iPad-Pro--11-inch-
    static let iPadPro_11_inch_1stGeneration: PreviewDevice = PreviewDevice(rawValue: "iPad Pro (11-inch) (1st generation)")

    /// iPad Pro (12.9-inch) (3rd generation)
    /// com.apple.CoreSimulator.SimDeviceType.iPad-Pro--12-9-inch---3rd-generation-
    static let iPadPro_12_9_inch_3rdGeneration: PreviewDevice = PreviewDevice(rawValue: "iPad Pro (12.9-inch) (3rd generation)")

    /// iPad Pro (11-inch) (2nd generation)
    /// com.apple.CoreSimulator.SimDeviceType.iPad-Pro--11-inch---2nd-generation-
    static let iPadPro_11_inch_2ndGeneration: PreviewDevice = PreviewDevice(rawValue: "iPad Pro (11-inch) (2nd generation)")

    /// iPad Pro (12.9-inch) (4th generation)
    /// com.apple.CoreSimulator.SimDeviceType.iPad-Pro--12-9-inch---4th-generation-
    static let iPadPro_12_9_inch_4thGeneration: PreviewDevice = PreviewDevice(rawValue: "iPad Pro (12.9-inch) (4th generation)")

    /// iPad mini (5th generation)
    /// com.apple.CoreSimulator.SimDeviceType.iPad-mini--5th-generation-
    static let iPadMini_5thGeneration: PreviewDevice = PreviewDevice(rawValue: "iPad mini (5th generation)")

    /// iPad Air (3rd generation)
    /// com.apple.CoreSimulator.SimDeviceType.iPad-Air--3rd-generation-
    static let iPadAir_3rdGeneration: PreviewDevice = PreviewDevice(rawValue: "iPad Air (3rd generation)")

    /// iPad (8th generation)
    /// com.apple.CoreSimulator.SimDeviceType.iPad--8th-generation-
    static let iPad_8thGeneration: PreviewDevice = PreviewDevice(rawValue: "iPad (8th generation)")

    /// iPad Air (4th generation)
    /// com.apple.CoreSimulator.SimDeviceType.iPad-Air--4th-generation-
    static let iPadAir_4thGeneration: PreviewDevice = PreviewDevice(rawValue: "iPad Air (4th generation)")

    /// iPad Pro (11-inch) (3rd generation)
    /// com.apple.CoreSimulator.SimDeviceType.iPad-Pro-11-inch-3rd-generation
    static let iPadPro_11_inch_3rdGeneration: PreviewDevice = PreviewDevice(rawValue: "iPad Pro (11-inch) (3rd generation)")

    /// iPad Pro (12.9-inch) (5th generation)
    /// com.apple.CoreSimulator.SimDeviceType.iPad-Pro-12-9-inch-5th-generation
    static let iPadPro_12_9_inch_5thGeneration: PreviewDevice = PreviewDevice(rawValue: "iPad Pro (12.9-inch) (5th generation)")

    /// Apple TV
    /// com.apple.CoreSimulator.SimDeviceType.Apple-TV-1080p
    static let appleTV: PreviewDevice = PreviewDevice(rawValue: "Apple TV")

    /// Apple TV 4K
    /// com.apple.CoreSimulator.SimDeviceType.Apple-TV-4K-4K
    static let appleTV4K: PreviewDevice = PreviewDevice(rawValue: "Apple TV 4K")

    /// Apple TV 4K (at 1080p)
    /// com.apple.CoreSimulator.SimDeviceType.Apple-TV-4K-1080p
    static let appleTV4K_at1080p: PreviewDevice = PreviewDevice(rawValue: "Apple TV 4K (at 1080p)")

    /// Apple TV 4K (2nd generation)
    /// com.apple.CoreSimulator.SimDeviceType.Apple-TV-4K-2nd-generation-4K
    static let appleTV4K_2ndGeneration: PreviewDevice = PreviewDevice(rawValue: "Apple TV 4K (2nd generation)")

    /// Apple TV 4K (at 1080p) (2nd generation)
    /// com.apple.CoreSimulator.SimDeviceType.Apple-TV-4K-2nd-generation-1080p
    static let appleTV4K_at1080p_2ndGeneration: PreviewDevice = PreviewDevice(rawValue: "Apple TV 4K (at 1080p) (2nd generation)")

    /// Apple Watch - 38mm
    /// com.apple.CoreSimulator.SimDeviceType.Apple-Watch-38mm
    static let appleWatch_38mm: PreviewDevice = PreviewDevice(rawValue: "Apple Watch - 38mm")

    /// Apple Watch - 42mm
    /// com.apple.CoreSimulator.SimDeviceType.Apple-Watch-42mm
    static let appleWatch_42mm: PreviewDevice = PreviewDevice(rawValue: "Apple Watch - 42mm")

    /// Apple Watch Series 2 - 38mm
    /// com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-2-38mm
    static let appleWatchSeries2_38mm: PreviewDevice = PreviewDevice(rawValue: "Apple Watch Series 2 - 38mm")

    /// Apple Watch Series 2 - 42mm
    /// com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-2-42mm
    static let appleWatchSeries2_42mm: PreviewDevice = PreviewDevice(rawValue: "Apple Watch Series 2 - 42mm")

    /// Apple Watch Series 3 - 38mm
    /// com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-3-38mm
    static let appleWatchSeries3_38mm: PreviewDevice = PreviewDevice(rawValue: "Apple Watch Series 3 - 38mm")

    /// Apple Watch Series 3 - 42mm
    /// com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-3-42mm
    static let appleWatchSeries3_42mm: PreviewDevice = PreviewDevice(rawValue: "Apple Watch Series 3 - 42mm")

    /// Apple Watch Series 4 - 40mm
    /// com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-4-40mm
    static let appleWatchSeries4_40mm: PreviewDevice = PreviewDevice(rawValue: "Apple Watch Series 4 - 40mm")

    /// Apple Watch Series 4 - 44mm
    /// com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-4-44mm
    static let appleWatchSeries4_44mm: PreviewDevice = PreviewDevice(rawValue: "Apple Watch Series 4 - 44mm")

    /// Apple Watch Series 5 - 40mm
    /// com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-5-40mm
    static let appleWatchSeries5_40mm: PreviewDevice = PreviewDevice(rawValue: "Apple Watch Series 5 - 40mm")

    /// Apple Watch Series 5 - 44mm
    /// com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-5-44mm
    static let appleWatchSeries5_44mm: PreviewDevice = PreviewDevice(rawValue: "Apple Watch Series 5 - 44mm")

    /// Apple Watch SE - 40mm
    /// com.apple.CoreSimulator.SimDeviceType.Apple-Watch-SE-40mm
    static let appleWatchSE_40mm: PreviewDevice = PreviewDevice(rawValue: "Apple Watch SE - 40mm")

    /// Apple Watch SE - 44mm
    /// com.apple.CoreSimulator.SimDeviceType.Apple-Watch-SE-44mm
    static let appleWatchSE_44mm: PreviewDevice = PreviewDevice(rawValue: "Apple Watch SE - 44mm")

    /// Apple Watch Series 6 - 40mm
    /// com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-6-40mm
    static let appleWatchSeries6_40mm: PreviewDevice = PreviewDevice(rawValue: "Apple Watch Series 6 - 40mm")

    /// Apple Watch Series 6 - 44mm
    /// com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-6-44mm
    static let appleWatchSeries6_44mm: PreviewDevice = PreviewDevice(rawValue: "Apple Watch Series 6 - 44mm")
}
