/// Generated by DeviceTypesGen

public enum DeviceType: String, CaseIterable {
    /// iPhone 4s
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-4s
    case iPhone4s = "iPhone 4s"

    /// iPhone 5
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-5
    case iPhone5 = "iPhone 5"

    /// iPhone 5s
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-5s
    case iPhone5s = "iPhone 5s"

    /// iPhone 6 Plus
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus
    case iPhone6Plus = "iPhone 6 Plus"

    /// iPhone 6
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-6
    case iPhone6 = "iPhone 6"

    /// iPhone 6s
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-6s
    case iPhone6s = "iPhone 6s"

    /// iPhone 6s Plus
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-6s-Plus
    case iPhone6sPlus = "iPhone 6s Plus"

    /// iPhone SE (1st generation)
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-SE
    case iPhoneSE_1stGeneration = "iPhone SE (1st generation)"

    /// iPhone 7
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-7
    case iPhone7 = "iPhone 7"

    /// iPhone 7 Plus
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-7-Plus
    case iPhone7Plus = "iPhone 7 Plus"

    /// iPhone 8
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-8
    case iPhone8 = "iPhone 8"

    /// iPhone 8 Plus
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-8-Plus
    case iPhone8Plus = "iPhone 8 Plus"

    /// iPhone X
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-X
    case iPhoneX = "iPhone X"

    /// iPhone Xs
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-XS
    case iPhoneXs = "iPhone Xs"

    /// iPhone Xs Max
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-XS-Max
    case iPhoneXsMax = "iPhone Xs Max"

    /// iPhone Xʀ
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-XR
    case iPhoneXʀ = "iPhone Xʀ"

    /// iPhone 11
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-11
    case iPhone11 = "iPhone 11"

    /// iPhone 11 Pro
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-11-Pro
    case iPhone11Pro = "iPhone 11 Pro"

    /// iPhone 11 Pro Max
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-11-Pro-Max
    case iPhone11ProMax = "iPhone 11 Pro Max"

    /// iPhone SE (2nd generation)
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-SE--2nd-generation-
    case iPhoneSE_2ndGeneration = "iPhone SE (2nd generation)"

    /// iPhone 12 mini
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-12-mini
    case iPhone12Mini = "iPhone 12 mini"

    /// iPhone 12
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-12
    case iPhone12 = "iPhone 12"

    /// iPhone 12 Pro
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-12-Pro
    case iPhone12Pro = "iPhone 12 Pro"

    /// iPhone 12 Pro Max
    /// com.apple.CoreSimulator.SimDeviceType.iPhone-12-Pro-Max
    case iPhone12ProMax = "iPhone 12 Pro Max"

    /// iPod touch (7th generation)
    /// com.apple.CoreSimulator.SimDeviceType.iPod-touch--7th-generation-
    case iPodTouch_7thGeneration = "iPod touch (7th generation)"

    /// iPad 2
    /// com.apple.CoreSimulator.SimDeviceType.iPad-2
    case iPad2 = "iPad 2"

    /// iPad Retina
    /// com.apple.CoreSimulator.SimDeviceType.iPad-Retina
    case iPadRetina = "iPad Retina"

    /// iPad Air
    /// com.apple.CoreSimulator.SimDeviceType.iPad-Air
    case iPadAir = "iPad Air"

    /// iPad mini 2
    /// com.apple.CoreSimulator.SimDeviceType.iPad-mini-2
    case iPadMini2 = "iPad mini 2"

    /// iPad mini 3
    /// com.apple.CoreSimulator.SimDeviceType.iPad-mini-3
    case iPadMini3 = "iPad mini 3"

    /// iPad mini 4
    /// com.apple.CoreSimulator.SimDeviceType.iPad-mini-4
    case iPadMini4 = "iPad mini 4"

    /// iPad Air 2
    /// com.apple.CoreSimulator.SimDeviceType.iPad-Air-2
    case iPadAir2 = "iPad Air 2"

    /// iPad Pro (9.7-inch)
    /// com.apple.CoreSimulator.SimDeviceType.iPad-Pro--9-7-inch-
    case iPadPro_9_7_inch = "iPad Pro (9.7-inch)"

    /// iPad Pro (12.9-inch) (1st generation)
    /// com.apple.CoreSimulator.SimDeviceType.iPad-Pro
    case iPadPro_12_9_inch_1stGeneration = "iPad Pro (12.9-inch) (1st generation)"

    /// iPad (5th generation)
    /// com.apple.CoreSimulator.SimDeviceType.iPad--5th-generation-
    case iPad_5thGeneration = "iPad (5th generation)"

    /// iPad Pro (12.9-inch) (2nd generation)
    /// com.apple.CoreSimulator.SimDeviceType.iPad-Pro--12-9-inch---2nd-generation-
    case iPadPro_12_9_inch_2ndGeneration = "iPad Pro (12.9-inch) (2nd generation)"

    /// iPad Pro (10.5-inch)
    /// com.apple.CoreSimulator.SimDeviceType.iPad-Pro--10-5-inch-
    case iPadPro_10_5_inch = "iPad Pro (10.5-inch)"

    /// iPad (6th generation)
    /// com.apple.CoreSimulator.SimDeviceType.iPad--6th-generation-
    case iPad_6thGeneration = "iPad (6th generation)"

    /// iPad (7th generation)
    /// com.apple.CoreSimulator.SimDeviceType.iPad--7th-generation-
    case iPad_7thGeneration = "iPad (7th generation)"

    /// iPad Pro (11-inch) (1st generation)
    /// com.apple.CoreSimulator.SimDeviceType.iPad-Pro--11-inch-
    case iPadPro_11_inch_1stGeneration = "iPad Pro (11-inch) (1st generation)"

    /// iPad Pro (12.9-inch) (3rd generation)
    /// com.apple.CoreSimulator.SimDeviceType.iPad-Pro--12-9-inch---3rd-generation-
    case iPadPro_12_9_inch_3rdGeneration = "iPad Pro (12.9-inch) (3rd generation)"

    /// iPad Pro (11-inch) (2nd generation)
    /// com.apple.CoreSimulator.SimDeviceType.iPad-Pro--11-inch---2nd-generation-
    case iPadPro_11_inch_2ndGeneration = "iPad Pro (11-inch) (2nd generation)"

    /// iPad Pro (12.9-inch) (4th generation)
    /// com.apple.CoreSimulator.SimDeviceType.iPad-Pro--12-9-inch---4th-generation-
    case iPadPro_12_9_inch_4thGeneration = "iPad Pro (12.9-inch) (4th generation)"

    /// iPad mini (5th generation)
    /// com.apple.CoreSimulator.SimDeviceType.iPad-mini--5th-generation-
    case iPadMini_5thGeneration = "iPad mini (5th generation)"

    /// iPad Air (3rd generation)
    /// com.apple.CoreSimulator.SimDeviceType.iPad-Air--3rd-generation-
    case iPadAir_3rdGeneration = "iPad Air (3rd generation)"

    /// iPad (8th generation)
    /// com.apple.CoreSimulator.SimDeviceType.iPad--8th-generation-
    case iPad_8thGeneration = "iPad (8th generation)"

    /// iPad Air (4th generation)
    /// com.apple.CoreSimulator.SimDeviceType.iPad-Air--4th-generation-
    case iPadAir_4thGeneration = "iPad Air (4th generation)"

    /// Apple TV
    /// com.apple.CoreSimulator.SimDeviceType.Apple-TV-1080p
    case appleTV = "Apple TV"

    /// Apple TV 4K
    /// com.apple.CoreSimulator.SimDeviceType.Apple-TV-4K-4K
    case appleTV4K = "Apple TV 4K"

    /// Apple TV 4K (at 1080p)
    /// com.apple.CoreSimulator.SimDeviceType.Apple-TV-4K-1080p
    case appleTV4K_at1080p = "Apple TV 4K (at 1080p)"

    /// Apple Watch - 38mm
    /// com.apple.CoreSimulator.SimDeviceType.Apple-Watch-38mm
    case appleWatch_38mm = "Apple Watch - 38mm"

    /// Apple Watch - 42mm
    /// com.apple.CoreSimulator.SimDeviceType.Apple-Watch-42mm
    case appleWatch_42mm = "Apple Watch - 42mm"

    /// Apple Watch Series 2 - 38mm
    /// com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-2-38mm
    case appleWatchSeries2_38mm = "Apple Watch Series 2 - 38mm"

    /// Apple Watch Series 2 - 42mm
    /// com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-2-42mm
    case appleWatchSeries2_42mm = "Apple Watch Series 2 - 42mm"

    /// Apple Watch Series 3 - 38mm
    /// com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-3-38mm
    case appleWatchSeries3_38mm = "Apple Watch Series 3 - 38mm"

    /// Apple Watch Series 3 - 42mm
    /// com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-3-42mm
    case appleWatchSeries3_42mm = "Apple Watch Series 3 - 42mm"

    /// Apple Watch Series 4 - 40mm
    /// com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-4-40mm
    case appleWatchSeries4_40mm = "Apple Watch Series 4 - 40mm"

    /// Apple Watch Series 4 - 44mm
    /// com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-4-44mm
    case appleWatchSeries4_44mm = "Apple Watch Series 4 - 44mm"

    /// Apple Watch Series 5 - 40mm
    /// com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-5-40mm
    case appleWatchSeries5_40mm = "Apple Watch Series 5 - 40mm"

    /// Apple Watch Series 5 - 44mm
    /// com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-5-44mm
    case appleWatchSeries5_44mm = "Apple Watch Series 5 - 44mm"

    /// Apple Watch SE - 40mm
    /// com.apple.CoreSimulator.SimDeviceType.Apple-Watch-SE-40mm
    case appleWatchSE_40mm = "Apple Watch SE - 40mm"

    /// Apple Watch SE - 44mm
    /// com.apple.CoreSimulator.SimDeviceType.Apple-Watch-SE-44mm
    case appleWatchSE_44mm = "Apple Watch SE - 44mm"

    /// Apple Watch Series 6 - 40mm
    /// com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-6-40mm
    case appleWatchSeries6_40mm = "Apple Watch Series 6 - 40mm"

    /// Apple Watch Series 6 - 44mm
    /// com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-6-44mm
    case appleWatchSeries6_44mm = "Apple Watch Series 6 - 44mm"
}

// ----

import SwiftUI

extension PreviewDevice {
    init(_ deviceType: DeviceType) {
        self.init(rawValue: deviceType.rawValue)
    }
}

extension View {
    func previewDevice(_ deviceType: DeviceType) -> some View {
        previewDevice(PreviewDevice(deviceType))
    }
}
