//
//  File.swift
//  
//
//  Created by Tomoya Hirano on 2021/06/30.
//

import Foundation

struct DeviceTypesCodeGenerator {
    let deviceTypes: [DeviceType]
    
    func variableName(_ string: String) -> String {
        string
            .split(separator: " ")
            .map({ $0.prefix(1).uppercased() + $0.dropFirst() })
            .joined()
            .replacingOccurrences(of: "-", with: "_")
            .replacingOccurrences(of: "(", with: "_")
            .replacingOccurrences(of: ")", with: "")
            .replacingOccurrences(of: ".", with: "_")
            .lowercasedFirstLetter()
    }
    
    func previewDeviceCode(_ deviceType: DeviceType) -> String {
        """
            /// \(deviceType.name)
            /// \(deviceType.identifier)
            static let \(variableName(deviceType.name)): PreviewDevice = PreviewDevice(rawValue: "\(deviceType.name)")
        """
    }
    
    func previewDeviceCodes() -> String {
        deviceTypes.map(previewDeviceCode(_:)).joined(separator: "\n\n")
    }
    
    func generate() -> String {
        """
        /// Generated by DeviceTypesGen
        
        import SwiftUI
        
        public extension PreviewDevice {
        \(previewDeviceCodes())
        }
        """
    }
}

extension String {
    func strip<T: StringProtocol>(_ string: T) -> String {
        self.replacingOccurrences(of: string, with: "")
    }
    
    func lowercasedFirstLetter() -> String {
      prefix(1).lowercased() + self.dropFirst()
    }
}
